# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from backend.session import SESSION
from backend.chat_logic import (send_message, get_message, load_chat_users)
import sys


class Ui_ChatForm(object):
    def load_messages(self):
        if not hasattr(self, "receiver_id"):
            return
            
        from backend.session import SESSION
        current_user = SESSION.get("user_id")
        
        if not current_user:
            return

        messages = get_message(current_user, self.receiver_id)
        self.list_messages.clear()
        for m in messages:
            # --- FIX: Corrected bracket placement syntax format ---
            self.list_messages.addItem(
                f"{m['sender_id']}: {m['message']}"
            )

    def open_chat(self, item):
        self.receiver_id = item.text()
        self.label_chat_name.setText(f"Chat with {self.receiver_id}")
        self.load_messages()

    def filter_users(self, text):
        for i in range (self.list_friends.count()):
            item = self.list_friends.item(i)
            item.setHidden(text.lower() not in item.text().lower())

    def send_messages(self):
        text = self.input_message.text().strip()  
        if not text or not hasattr(self, "receiver_id"):
            return
        success = send_message(self.current_user, self.receiver_id, text)
        if success:
            self.input_message.clear()
            self.load_messages()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(820, 600)
        Form.setStyleSheet("""
        QWidget {
            background-color: #F0F4FA;
            font-family: "Segoe UI", sans-serif;
        }

        QListWidget#list_friends {
            background-color: #FFFFFF;
            border-radius: 10px;
            border: none;
            padding: 10px;
            font-size: 14px;
        }

        QListWidget#list_messages {
            background-color: #E2EAF5;
            border-radius: 10px;
            border: none;
            padding: 15px;
            font-size: 14px;
        }

        QLineEdit {
            background-color: #FFFFFF;
            border: 1px solid #D1D9E6;
            border-radius: 15px;
            padding: 10px;
            font-size: 14px;
        }

        QLineEdit:focus {
            border: 1px solid #1877F2;
        }

        QPushButton#btn_send {
            background-color: #1877F2;
            color: white;
            border-radius: 15px;
            padding: 10px 20px;
            font-weight: bold;
            font-size: 14px;
        }

        QPushButton#btn_send:hover {
            background-color: #166FE5;
        }

        QLabel#label_chat_name {
            font-size: 16px;
            font-weight: bold;
            padding: 10px;
            background-color: white;
            border-radius: 10px;
        }
        """)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.input_search = QtWidgets.QLineEdit(self.widget)

        self.input_search.textChanged.connect(self.filter_users)
        self.input_search.setObjectName("input_search")
        self.verticalLayout.addWidget(self.input_search)

        self.list_friends = QtWidgets.QListWidget(self.widget)

        self.current_user = "user_id_here"
        self.receiver_id = None
        
        self.list_friends.setObjectName("list_friends")
        self.verticalLayout.addWidget(self.list_friends)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_chat_name = QtWidgets.QLabel(self.widget_2)
        self.label_chat_name.setObjectName("label_chat_name")
        self.verticalLayout_2.addWidget(self.label_chat_name)
        self.list_messages = QtWidgets.QListWidget(self.widget_2)
        self.list_messages.setObjectName("list_messages")
        self.verticalLayout_2.addWidget(self.list_messages)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_message = QtWidgets.QLineEdit(self.widget_2)
        self.input_message.setObjectName("input_message")
        self.horizontalLayout_3.addWidget(self.input_message)
        self.btn_send = QtWidgets.QPushButton(self.widget_2)
        self.btn_send.setObjectName("btn_send")
        self.btn_send.clicked.connect(self.send_messages)
        self.horizontalLayout_3.addWidget(self.btn_send)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.list_friends.itemClicked.connect(self.open_chat)
        self.btn_send.setText(_translate("Form", "PushButton"))
        self.input_search.setPlaceholderText("Search users...")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_ChatForm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
    