# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

import sys
import os

sys.path.append(
    os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..")
    )
)

from backend import chat_logic            # import chatlogic.py function to ui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(819, 600)
        Form.setStyleSheet("QWidget { background-color: #F0F4FA; font-family: \"Segoe UI\", sans-serif; }\n"
"QListWidget#list_friends { background-color: #FFFFFF; border-radius: 10px; border: none; padding: 10px; font-size: 14px; }\n"
"QListWidget#list_messages { background-color: #E2EAF5; border-radius: 10px; border: none; padding: 15px; font-size: 14px; }\n"
"QLineEdit { background-color: #FFFFFF; border: 1px solid #D1D9E6; border-radius: 15px; padding: 10px; font-size: 14px; }\n"
"QLineEdit:focus { border: 1px solid #1877F2; }\n"
"QPushButton#btn_send { background-color: #1877F2; color: white; border-radius: 15px; padding: 10px 20px; font-weight: bold; font-size: 14px; }\n"
"QPushButton#btn_send:hover { background-color: #166FE5; }\n"
"QLabel#label_chat_name { font-size: 16px; font-weight: bold; padding: 10px; background-color: white; border-radius: 10px; }")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_search = QtWidgets.QLineEdit(self.widget)
        self.input_search.setObjectName("input_search")
        self.verticalLayout.addWidget(self.input_search)
        self.list_friends = QtWidgets.QListWidget(self.widget)
        self.list_friends.setObjectName("list_friends")
        self.verticalLayout.addWidget(self.list_friends)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_chat_name = QtWidgets.QLabel(self.widget_2)
        self.label_chat_name.setObjectName("label_chat_name")
        self.verticalLayout_2.addWidget(self.label_chat_name)
        self.list_messages = QtWidgets.QListWidget(self.widget_2)
        self.list_messages.setObjectName("list_messages")
        self.verticalLayout_2.addWidget(self.list_messages)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_message = QtWidgets.QLineEdit(self.widget_2)
        self.input_message.setObjectName("input_message")
        self.horizontalLayout_3.addWidget(self.input_message)
        self.btn_send = QtWidgets.QPushButton(self.widget_2)
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_3.addWidget(self.btn_send)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.btn_send.clicked.connect(self.send_message_ui)      #bjuyu
            
        def send_message_ui(self):                                     #bjuyu
            message = self.input_message.text()
            if message == "":
                return
            sender_id = 1
            receiver_id = 2
            result = chat_logic.send_message(
                sender_id,
                receiver_id,
                message
            )
            self.list_messages.addItem("You: " + message)
            self.input_message.clear()
            print(result)                                        #bjuyu

        def retranslateUi(self, Form):  
            _translate = QtCore.QCoreApplication.translate
            Form.setWindowTitle(_translate("Form", "Form"))
            self.label_chat_name.setText(_translate("Form", "TextLabel"))
            self.btn_send.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
