# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interest.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("/* Main Window Background */\n"
"QWidget#centralwidget {\n"
"    background-color: #f0f2f5;\n"
"}\n"
"\n"
"/* Style the \'Select Your Interests\' Container */\n"
"QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 8px;\n"
"    margin-top: 20px; \n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Style the Group Box Title */\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 10px;\n"
"    color: #1f2937;\n"
"}\n"
"\n"
"/* Style the Checkboxes */\n"
"QCheckBox {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 13px;\n"
"    color: #4b5563;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    color: #2563eb; \n"
"}\n"
"\n"
"/* Style the Submit Button */\n"
"QPushButton#btn_submit {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 10px 20px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton#btn_submit:hover {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"\n"
"QPushButton#btn_submit:pressed {\n"
"    background-color: #1e40af;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chk_games = QtWidgets.QCheckBox(self.groupBox)
        self.chk_games.setObjectName("chk_games")
        self.verticalLayout_2.addWidget(self.chk_games)
        self.chk_music = QtWidgets.QCheckBox(self.groupBox)
        self.chk_music.setObjectName("chk_music")
        self.verticalLayout_2.addWidget(self.chk_music)
        self.chk_tech = QtWidgets.QCheckBox(self.groupBox)
        self.chk_tech.setObjectName("chk_tech")
        self.verticalLayout_2.addWidget(self.chk_tech)
        self.chk_cooking = QtWidgets.QCheckBox(self.groupBox)
        self.chk_cooking.setObjectName("chk_cooking")
        self.verticalLayout_2.addWidget(self.chk_cooking)
        self.chk_art = QtWidgets.QCheckBox(self.groupBox)
        self.chk_art.setObjectName("chk_art")
        self.verticalLayout_2.addWidget(self.chk_art)
        self.chk_books = QtWidgets.QCheckBox(self.groupBox)
        self.chk_books.setObjectName("chk_books")
        self.verticalLayout_2.addWidget(self.chk_books)
        self.chk_sports = QtWidgets.QCheckBox(self.groupBox)
        self.chk_sports.setObjectName("chk_sports")
        self.verticalLayout_2.addWidget(self.chk_sports)
        self.chk_traveling = QtWidgets.QCheckBox(self.groupBox)
        self.chk_traveling.setObjectName("chk_traveling")
        self.verticalLayout_2.addWidget(self.chk_traveling)
        self.chk_movies = QtWidgets.QCheckBox(self.groupBox)
        self.chk_movies.setObjectName("chk_movies")
        self.verticalLayout_2.addWidget(self.chk_movies)
        self.chk_photography = QtWidgets.QCheckBox(self.groupBox)
        self.chk_photography.setObjectName("chk_photography")
        self.verticalLayout_2.addWidget(self.chk_photography)
        self.verticalLayout.addWidget(self.groupBox)
        self.btn_submit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_submit.setObjectName("btn_submit")
        self.verticalLayout.addWidget(self.btn_submit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Select Your Interests"))
        self.chk_games.setText(_translate("MainWindow", "Playing Games"))
        self.chk_music.setText(_translate("MainWindow", "Listening to Music"))
        self.chk_tech.setText(_translate("MainWindow", "Coding & Tech"))
        self.chk_cooking.setText(_translate("MainWindow", "Cooking"))
        self.chk_art.setText(_translate("MainWindow", "Art & Design"))
        self.chk_books.setText(_translate("MainWindow", "Reading Books"))
        self.chk_sports.setText(_translate("MainWindow", "Sports & Fitness"))
        self.chk_traveling.setText(_translate("MainWindow", "Traveling"))
        self.chk_movies.setText(_translate("MainWindow", "Watching Movies"))
        self.chk_photography.setText(_translate("MainWindow", "Photography"))
        self.btn_submit.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
