# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zest_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 612)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f0f2f5;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setMinimumSize(QtCore.QSize(200, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_logo = QtWidgets.QLabel(self.sidebar)
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout_4.addWidget(self.label_logo)
        self.btn_feed = QtWidgets.QPushButton(self.sidebar)
        self.btn_feed.setObjectName("btn_feed")
        self.verticalLayout_4.addWidget(self.btn_feed)
        self.btn_explore = QtWidgets.QPushButton(self.sidebar)
        self.btn_explore.setObjectName("btn_explore")
        self.verticalLayout_4.addWidget(self.btn_explore)
        self.btn_videos = QtWidgets.QPushButton(self.sidebar)
        self.btn_videos.setObjectName("btn_videos")
        self.verticalLayout_4.addWidget(self.btn_videos)
        self.btn_groups = QtWidgets.QPushButton(self.sidebar)
        self.btn_groups.setObjectName("btn_groups")
        self.verticalLayout_4.addWidget(self.btn_groups)
        self.btn_profile = QtWidgets.QPushButton(self.sidebar)
        self.btn_profile.setObjectName("btn_profile")
        self.verticalLayout_4.addWidget(self.btn_profile)
        spacerItem = QtWidgets.QSpacerItem(20, 376, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.sidebar)
        self.feed_container = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feed_container.sizePolicy().hasHeightForWidth())
        self.feed_container.setSizePolicy(sizePolicy)
        self.feed_container.setMinimumSize(QtCore.QSize(400, 0))
        self.feed_container.setMaximumSize(QtCore.QSize(250, 16777215))
        self.feed_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.feed_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.feed_container.setObjectName("feed_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.feed_container)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.feed_container)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.header_frame)
        self.lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.header_frame)
        self.label.setStyleSheet("font-size: 24px;\n"
"font-weight: bold;\n"
"color: #1c1e21;\n"
"padding-left: 10px;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.scrollArea = QtWidgets.QScrollArea(self.feed_container)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 361, 852))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.post_placeholder = QtWidgets.QFrame(self.widget)
        self.post_placeholder.setStyleSheet("#post_placeholder {\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #e0e0e0;\n"
"}")
        self.post_placeholder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post_placeholder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post_placeholder.setObjectName("post_placeholder")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.post_placeholder)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_username = QtWidgets.QLabel(self.post_placeholder)
        self.label_username.setStyleSheet("font-weight: bold;\n"
"font-size: 15px;\n"
"color: #1c1e21;")
        self.label_username.setObjectName("label_username")
        self.verticalLayout_5.addWidget(self.label_username)
        self.label_text = QtWidgets.QLabel(self.post_placeholder)
        self.label_text.setStyleSheet("font-weight: bold;\n"
"font-size: 15px;\n"
"color: #1c1e21;")
        self.label_text.setObjectName("label_text")
        self.verticalLayout_5.addWidget(self.label_text)
        self.label_image = QtWidgets.QLabel(self.post_placeholder)
        self.label_image.setStyleSheet("background-color: #e4e6eb;\n"
"border-radius: 8px;\n"
"min-height: 200px;")
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.verticalLayout_5.addWidget(self.label_image)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.post_placeholder_3 = QtWidgets.QFrame(self.post_placeholder)
        self.post_placeholder_3.setStyleSheet("#post_placeholder {\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #e0e0e0;\n"
"}")
        self.post_placeholder_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post_placeholder_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post_placeholder_3.setObjectName("post_placeholder_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.post_placeholder_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_username_6 = QtWidgets.QLabel(self.post_placeholder_3)
        self.label_username_6.setStyleSheet("font-weight: bold;\n"
"font-size: 15px;\n"
"color: #1c1e21;")
        self.label_username_6.setObjectName("label_username_6")
        self.verticalLayout_10.addWidget(self.label_username_6)
        self.label_text_6 = QtWidgets.QLabel(self.post_placeholder_3)
        self.label_text_6.setStyleSheet("font-weight: bold;\n"
"font-size: 15px;\n"
"color: #1c1e21;")
        self.label_text_6.setObjectName("label_text_6")
        self.verticalLayout_10.addWidget(self.label_text_6)
        self.label_image_6 = QtWidgets.QLabel(self.post_placeholder_3)
        self.label_image_6.setStyleSheet("background-color: #e4e6eb;\n"
"border-radius: 8px;\n"
"min-height: 200px;")
        self.label_image_6.setText("")
        self.label_image_6.setObjectName("label_image_6")
        self.verticalLayout_10.addWidget(self.label_image_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.post_placeholder_3)
        self.post_placeholder_2 = QtWidgets.QFrame(self.post_placeholder)
        self.post_placeholder_2.setStyleSheet("#post_placeholder {\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid #e0e0e0;\n"
"}")
        self.post_placeholder_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post_placeholder_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post_placeholder_2.setObjectName("post_placeholder_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.post_placeholder_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_username_5 = QtWidgets.QLabel(self.post_placeholder_2)
        self.label_username_5.setStyleSheet("font-weight: bold;\n"
"font-size: 15px;\n"
"color: #1c1e21;")
        self.label_username_5.setObjectName("label_username_5")
        self.verticalLayout_9.addWidget(self.label_username_5)
        self.label_text_5 = QtWidgets.QLabel(self.post_placeholder_2)
        self.label_text_5.setStyleSheet("font-weight: bold;\n"
"font-size: 15px;\n"
"color: #1c1e21;")
        self.label_text_5.setObjectName("label_text_5")
        self.verticalLayout_9.addWidget(self.label_text_5)
        self.label_image_5 = QtWidgets.QLabel(self.post_placeholder_2)
        self.label_image_5.setStyleSheet("background-color: #e4e6eb;\n"
"border-radius: 8px;\n"
"min-height: 200px;")
        self.label_image_5.setText("")
        self.label_image_5.setObjectName("label_image_5")
        self.verticalLayout_9.addWidget(self.label_image_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.post_placeholder_2)
        self.verticalLayout_3.addWidget(self.post_placeholder)
        self.scrollArea.setWidget(self.widget)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.feed_container)
        self.right_panel = QtWidgets.QFrame(self.centralwidget)
        self.right_panel.setMinimumSize(QtCore.QSize(250, 0))
        self.right_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_panel.setObjectName("right_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_panel)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_messaging = QtWidgets.QPushButton(self.right_panel)
        self.btn_messaging.setObjectName("btn_messaging")
        self.verticalLayout.addWidget(self.btn_messaging)
        self.label_2 = QtWidgets.QLabel(self.right_panel)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.right_panel)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.btn_create_post = QtWidgets.QPushButton(self.right_panel)
        self.btn_create_post.setObjectName("btn_create_post")
        self.verticalLayout.addWidget(self.btn_create_post)
        self.label_4 = QtWidgets.QLabel(self.right_panel)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.list_groups = QtWidgets.QListWidget(self.right_panel)
        self.list_groups.setObjectName("list_groups")
        self.verticalLayout.addWidget(self.list_groups)
        self.list_messages = QtWidgets.QListWidget(self.right_panel)
        self.list_messages.setObjectName("list_messages")
        self.verticalLayout.addWidget(self.list_messages)
        self.horizontalLayout.addWidget(self.right_panel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_logo.setText(_translate("MainWindow", "ZEST"))
        self.btn_feed.setText(_translate("MainWindow", "Feed"))
        self.btn_explore.setText(_translate("MainWindow", "Explore"))
        self.btn_videos.setText(_translate("MainWindow", "Videos"))
        self.btn_groups.setText(_translate("MainWindow", "Groups"))
        self.btn_profile.setText(_translate("MainWindow", "Profile"))
        self.label.setText(_translate("MainWindow", "Global Feed"))
        self.label_username.setText(_translate("MainWindow", "mrfarhan"))
        self.label_text.setText(_translate("MainWindow", "\"This is my first post on Zest!\""))
        self.label_username_6.setText(_translate("MainWindow", "mrbalaa"))
        self.label_text_6.setText(_translate("MainWindow", "whats up peeps"))
        self.label_username_5.setText(_translate("MainWindow", "mrjaswin"))
        self.label_text_5.setText(_translate("MainWindow", "damnn nice app,love it "))
        self.btn_messaging.setText(_translate("MainWindow", "New Message"))
        self.label_2.setText(_translate("MainWindow", "Community Hub"))
        self.label_3.setText(_translate("MainWindow", "Active Groups"))
        self.btn_create_post.setText(_translate("MainWindow", "Create Post/Video"))
        self.label_4.setText(_translate("MainWindow", "Direct Messaging"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
